import Head from 'next/head'
import SearchAppBar from '../../components/SearchAppBar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokemon Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchAppBar></SearchAppBar>
    </>
  )
}
